[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/trade-appraisal"
  to = "/.netlify/functions/trade-appraisal"
  status = 200
