[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/trade-appraisal"
  to = "/.netlify/functions/trade-appraisal"
  status = 200


# Resolve /success and SPA-style fallback for deep links
[[redirects]]
  from = "/success"
  to = "/success/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
